import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import i from "../styles/Index.module.css";
//=========================================================
//=========================================================
import { menuOptionsContext } from "../contexts/changeMenuContext";
//=========================================================
import GameOptions from "../components/gameOptions/gameOptions";
import CreateGame from "../components/menu/createGame";
import JoinGame from "../components/menu/joinGame";
//=========================================================
//=========================================================

const Home: NextPage = () => {
  const [switchOptions, setSwitchOptions] = useState<any>("gameOptions");
  return (
    <div className={i.container}>
      <Head>
        <title>Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={i.main}>
        <menuOptionsContext.Provider
          value={{ switchOptions, setSwitchOptions }}
        >
          {switchOptions === "gameOptions" ? (
            <GameOptions />
          ) : switchOptions === "createGame" ? (
            <CreateGame />
          ) : switchOptions === "joinGame" ? (
            <JoinGame />
          ) : (
            ""
          )}
        </menuOptionsContext.Provider>
      </main>
      <footer className={i.footer}></footer>
    </div>
  );
};

export default Home;
